Queries
crismotinha/projetoBD pull request #15
Opened 2018-11-21 09:03 UTC by leticiavna

a 16 eu n tenho certeza se entendi direito o q a gente queria
resolve #7

2018-11-25 01:45 UTC, crismotinha requested changes

2018-11-25 01:45 UTC, crismotinha commented on queries.sql
> +    FROM Produto p, Venda v
```suggestion
    FROM Produto p
```
(já faz o inner com venda embaixo, se deixar esse aí dá erro)

2018-11-25 01:45 UTC, crismotinha commented on queries.sql
> +    	INNER JOIN EstoqueProduto ep ON p.id = ep.id_produto
Não deveria ser com receita? Pelo que entendi o peso total do produto seria tipo 100g de massa + 200g de carne = 300g, não entendi o join com estoque (e a query não funfou aqui de qq forma)

2018-11-25 01:45 UTC, crismotinha commented on queries.sql
> +-- 17. Numero de funcionarios por filial
essa ficou meio idiota :( na hora fez sentido mas é literalmente um campo, acho melhor deletar (por mais que vc tenha feito com o count, ainda assim é um campo kkk) e a gente pensa em outra melhor

2018-11-25 02:32 UTC, leticiavna commented on queries.sql
> +-- 17. Numero de funcionarios por filial
hehehehe blz, concordo, acho q na hora a gente não tinha pensado q viria a ser um campo

2018-11-28 01:27 UTC, crismotinha approved these changes

2018-11-28 01:27 UTC, merged